### ISSUE TITLE
Misbehaviour upon startup when command lines contain '%' character

### ISSUE THREAD

**Issue by Sebbyastian** [luluco250/SLEA#1]
The `fprintf` function expects format directives to be paired with arguments that aren't there, so when someone modifies the config to include '%' characters they might notice some misbehaviour.

I suggest using `fputs` (which, by the way, doesn't append an extra newline, unlike `puts`) here to avoid that issue.

**Comment by luluco250** [comment]
Thanks, I'll do an overhaul of this program with a more C++ style approach soon.
